<?php

return [
    [
        "user_id" => 8,
        "title" => "Sint sapiente nihil placeat corporis velit neque hic.",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 139,
        "address" => "Rotonda Tancredi 60 Appartamento 29\nClaudia calabro, 17924 Modena (CT)",
        "visibility" => 1,
        "slug" => "voluptatem-eum-id-excepturi-officia-at-et",
        "longitude" => 158.976775,
        "latitude" => 82.028437,
        "description" => "Voluptatem aliquam vero et cumque aut. Repellendus labore excepturi pariatur dolorem quibusdam autem. Quo qui facilis consequuntur minima tempora. Commodi non ut vel.",
        "price" => 607814.5936912926,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00dd66?text=apartments+perspiciatis"
    ],
    [
        "user_id" => 20,
        "title" => "Deleniti ipsum repellat ut impedit sunt.",
        "rooms" => 3,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 146,
        "address" => "Via Karim 492\nIvonne del friuli, 99153 Prato (VS)",
        "visibility" => 1,
        "slug" => "itaque-magni-autem-occaecati-omnis",
        "longitude" => -71.672535,
        "latitude" => -13.343564,
        "description" => "Corrupti tempora provident modi aut. Non quia aut iste quia. Et eos est sint amet quae suscipit assumenda. Ipsa aut explicabo eius quas sequi distinctio architecto. Repudiandae eligendi tempore aperiam autem vel.",
        "price" => 58250.28162833782,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/0011aa?text=apartments+maxime"
    ],
    [
        "user_id" => 46,
        "title" => "Voluptates voluptatum ipsa est neque mollitia minima.",
        "rooms" => 4,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 176,
        "address" => "Strada Guerra 12 Piano 8\nSesto Monia sardo, 45049 Varese (AQ)",
        "visibility" => 0,
        "slug" => "autem-accusantium-quo-nam-et-repellendus-in",
        "longitude" => -112.468332,
        "latitude" => 52.696017,
        "description" => "Qui totam quod aperiam quis veritatis sit ullam. Incidunt quidem ut dicta autem. Adipisci nemo ipsum odio iure molestias velit eligendi. Voluptas quos eaque qui qui debitis porro corrupti enim. Eligendi ut expedita qui.",
        "price" => 292753.3973114348,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00ffee?text=apartments+nemo"
    ],
    [
        "user_id" => 12,
        "title" => "Minus rem et nihil similique.",
        "rooms" => 4,
        "bedrooms" => 1,
        "bathrooms" => 2,
        "square_meters" => 151,
        "address" => "Strada Basile 553 Piano 4\nDonati lido, 51286 Napoli (RC)",
        "visibility" => 0,
        "slug" => "occaecati-est-nostrum-non-voluptatem-occaecati",
        "longitude" => 15.949334,
        "latitude" => 13.087353,
        "description" => "Aut exercitationem molestias nam architecto a aut deserunt. Quae accusantium voluptatem expedita velit et corporis. In voluptatem culpa quo sint dolorum.",
        "price" => 359005.83127001574,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/005599?text=apartments+soluta"
    ],
    [
        "user_id" => 10,
        "title" => "Quae iste ducimus impedit iure.",
        "rooms" => 2,
        "bedrooms" => 1,
        "bathrooms" => 2,
        "square_meters" => 168,
        "address" => "Contrada De rosa 1 Piano 6\nSan Joshua, 70878 Agrigento (LU)",
        "visibility" => 1,
        "slug" => "neque-ut-sed-earum",
        "longitude" => 158.974908,
        "latitude" => 76.402409,
        "description" => "Aliquam architecto incidunt rem debitis aperiam et excepturi. Aspernatur est et ut est excepturi.",
        "price" => 338227.37187064596,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/000000?text=apartments+minima"
    ],
    [
        "user_id" => 11,
        "title" => "Optio exercitationem omnis reiciendis fuga explicabo totam.",
        "rooms" => 4,
        "bedrooms" => 1,
        "bathrooms" => 2,
        "square_meters" => 137,
        "address" => "Contrada Rizzo 77 Piano 5\nColombo umbro, 18249 Gorizia (MT)",
        "visibility" => 0,
        "slug" => "quo-et-ut-et-molestias-eos-quis-occaecati-error",
        "longitude" => -176.531972,
        "latitude" => -33.107962,
        "description" => "Similique in natus consequatur nesciunt. Qui autem suscipit qui velit sit voluptatum omnis et. Modi nihil nam quia mollitia. Praesentium numquam quaerat labore illo omnis voluptatem.",
        "price" => 965248.1961740406,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/003366?text=apartments+illum"
    ],
    [
        "user_id" => 37,
        "title" => "Cumque itaque alias facere reiciendis officiis vel consequatur dolorum.",
        "rooms" => 3,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 173,
        "address" => "Strada Russo 4\nBorgo Grazia calabro, 90884 Lucca (CN)",
        "visibility" => 0,
        "slug" => "cupiditate-repellendus-quod-vel-dolores-eos",
        "longitude" => 85.578065,
        "latitude" => -64.025144,
        "description" => "Temporibus magnam esse fuga animi ut quo. Suscipit ut accusantium aut quam mollitia impedit totam. Non sit adipisci quas libero.",
        "price" => 497010.0304051349,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/000033?text=apartments+aut"
    ],
    [
        "user_id" => 30,
        "title" => "Eum nihil quae tenetur laudantium.",
        "rooms" => 2,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 84,
        "address" => "Via Marianita 452\nQuarto Max calabro, 61602 Brescia (RC)",
        "visibility" => 0,
        "slug" => "aut-unde-omnis-maiores-incidunt",
        "longitude" => -128.583175,
        "latitude" => 9.697423,
        "description" => "Blanditiis qui ea accusamus. Officia non pariatur voluptas rerum earum nulla qui. Incidunt fugiat molestias placeat dolorum est.",
        "price" => 792747.3182709643,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00ddcc?text=apartments+a"
    ],
    [
        "user_id" => 39,
        "title" => "Saepe et ullam debitis ea ut velit sint.",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 72,
        "address" => "Rotonda Danthon 5\nRadio veneto, 34124 Gorizia (BR)",
        "visibility" => 1,
        "slug" => "vel-et-qui-impedit-suscipit",
        "longitude" => -114.179802,
        "latitude" => -1.443268,
        "description" => "Deserunt possimus ut debitis. Molestiae quos blanditiis tempore amet. Rerum vitae aspernatur vel natus ipsum.",
        "price" => 31676.084367407526,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00eeaa?text=apartments+et"
    ],
    [
        "user_id" => 28,
        "title" => "Et ut qui blanditiis.",
        "rooms" => 1,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 65,
        "address" => "Contrada Barone 3 Piano 4\nSettimo Gaetano terme, 87090 Bergamo (MT)",
        "visibility" => 0,
        "slug" => "fugiat-nisi-omnis-reprehenderit",
        "longitude" => -101.077928,
        "latitude" => -17.217678,
        "description" => "Praesentium aut voluptatem vitae similique est. Amet ipsa quae non. Laborum velit molestiae suscipit tempore iure neque et pariatur.",
        "price" => 663959.821478445,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00dd66?text=apartments+quis"
    ],
    [
        "user_id" => 25,
        "title" => "Nihil et repellendus minus architecto molestiae.",
        "rooms" => 2,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 135,
        "address" => "Via Pietro 27 Appartamento 73\nSan Flavio del friuli, 67284 Messina (OG)",
        "visibility" => 0,
        "slug" => "atque-dolorem-consequatur-blanditiis-et-officia",
        "longitude" => 173.379271,
        "latitude" => 32.930768,
        "description" => "Aut quaerat et hic illum et. Ut facilis dolores nam ratione molestias. Distinctio doloribus accusantium ab non vero maxime. Itaque et molestiae et eos tempora. Eum officia saepe laudantium laborum pariatur consequuntur accusantium.",
        "price" => 114540.0777154323,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/006655?text=apartments+cumque"
    ],
    [
        "user_id" => 38,
        "title" => "Architecto voluptatem cumque nostrum tempora.",
        "rooms" => 5,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 151,
        "address" => "Strada Michael 27 Appartamento 19\nEvita umbro, 75839 Imperia (TS)",
        "visibility" => 1,
        "slug" => "similique-odit-libero-voluptatem-et",
        "longitude" => 143.744174,
        "latitude" => 22.758526,
        "description" => "Unde dolor porro deleniti necessitatibus. Voluptatibus necessitatibus dolore libero dolore qui.",
        "price" => 739914.0545585724,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/0000cc?text=apartments+qui"
    ],
    [
        "user_id" => 7,
        "title" => "Ullam blanditiis est illo qui veritatis dolores.",
        "rooms" => 4,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 93,
        "address" => "Borgo Donati 668\nSesto Ilario, 57386 Venezia (CA)",
        "visibility" => 1,
        "slug" => "aut-odit-voluptatem-sapiente-aut-necessitatibus",
        "longitude" => -178.380793,
        "latitude" => -68.981599,
        "description" => "Et voluptatem id est aliquid quo ullam et. Quibusdam praesentium a inventore dolorem ea harum aut explicabo. Ut omnis rem iusto quos dolore.",
        "price" => 61835.834459325226,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/0044cc?text=apartments+dolor"
    ],
    [
        "user_id" => 32,
        "title" => "Sit sequi repellat nihil qui autem sit.",
        "rooms" => 4,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 78,
        "address" => "Incrocio Grassi 57 Piano 2\nRusso sardo, 28502 Ravenna (AR)",
        "visibility" => 0,
        "slug" => "cumque-commodi-exercitationem-repudiandae-eaque-commodi",
        "longitude" => 62.508389,
        "latitude" => 4.981184,
        "description" => "Praesentium atque porro fugiat sapiente voluptatem. Maiores maiores voluptatum vero est autem dolor. Velit qui tempora assumenda repudiandae alias expedita. Repudiandae voluptatem et aliquam vero.",
        "price" => 83313.8855096483,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/0022bb?text=apartments+et"
    ],
    [
        "user_id" => 29,
        "title" => "Eveniet ut voluptatem veritatis enim ut.",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 90,
        "address" => "Via Odino 4 Piano 0\nFerretti sardo, 91849 Mantova (SO)",
        "visibility" => 1,
        "slug" => "cum-ipsa-voluptas-deserunt-aut-autem-modi-aspernatur",
        "longitude" => -15.984209,
        "latitude" => -8.196968,
        "description" => "Autem sed ducimus ut aliquid ullam molestias dolorum magnam. Sint aut maiores numquam. Quas porro aut reiciendis in vitae impedit laudantium. Nihil quibusdam magnam at impedit voluptas sequi.",
        "price" => 112432.93183969005,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00dd44?text=apartments+perspiciatis"
    ],
    [
        "user_id" => 45,
        "title" => "Maxime modi omnis maxime et pariatur.",
        "rooms" => 4,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 143,
        "address" => "Via Rinaldi 53\nQuarto a mare, 89380 Avellino (CA)",
        "visibility" => 1,
        "slug" => "molestiae-quam-magni-est-quas-est-esse",
        "longitude" => -61.671147,
        "latitude" => -73.650871,
        "description" => "Ad velit omnis eum est corrupti. Ullam asperiores in dolores rerum et minima. Adipisci iste ab mollitia dolores voluptatem rerum. Asperiores deleniti corrupti aut ad sunt consectetur. Voluptate molestias placeat fugiat qui.",
        "price" => 706007.9573541917,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00bbcc?text=apartments+occaecati"
    ],
    [
        "user_id" => 27,
        "title" => "Et quia labore veniam eum nam nihil.",
        "rooms" => 2,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 75,
        "address" => "Strada Bernardo 7\nSan Loretta laziale, 91487 Ogliastra (FG)",
        "visibility" => 0,
        "slug" => "a-fugiat-eaque-nemo-quos-consequatur-est-et",
        "longitude" => -35.140487,
        "latitude" => 63.226505,
        "description" => "Repellat laudantium id ad debitis. Aut est odit voluptas iusto itaque. Quos dolor enim in praesentium dolorum suscipit possimus et. Sit ut ducimus eum beatae saepe non.",
        "price" => 522095.9372316003,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/008811?text=apartments+perspiciatis"
    ],
    [
        "user_id" => 7,
        "title" => "Vero tenetur est nihil odio est.",
        "rooms" => 1,
        "bedrooms" => 1,
        "bathrooms" => 2,
        "square_meters" => 199,
        "address" => "Contrada Longo 90\nBorgo Selvaggia veneto, 98185 Barletta-Andria-Trani (FC)",
        "visibility" => 0,
        "slug" => "nihil-qui-inventore-repellat-repellat-repellat-fugit",
        "longitude" => 77.980361,
        "latitude" => -20.548354,
        "description" => "Nam tempore et ut nulla aut. Magni perferendis hic fugit ullam quia debitis facere. Ad quia enim nulla dicta molestiae. Alias est veniam quo nam nulla. A voluptatem quaerat rerum sit aliquid.",
        "price" => 710194.3449537244,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/002277?text=apartments+enim"
    ],
    [
        "user_id" => 22,
        "title" => "Officiis quos vel quia.",
        "rooms" => 3,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 66,
        "address" => "Strada Piras 50 Appartamento 41\nGianmaria nell'emilia, 21815 Potenza (SO)",
        "visibility" => 1,
        "slug" => "cupiditate-quos-libero-et-dolorem-voluptatibus-aperiam",
        "longitude" => -98.633618,
        "latitude" => -31.699372,
        "description" => "Necessitatibus sed aut voluptatem. Autem sequi eos aliquid pariatur accusamus et possimus. Sequi ut aut animi quod.",
        "price" => 425507.9836237747,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/0011dd?text=apartments+mollitia"
    ],
    [
        "user_id" => 11,
        "title" => "Animi quod in rerum et velit accusantium laudantium.",
        "rooms" => 3,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 147,
        "address" => "Rotonda Ruggiero 26 Piano 8\nOsea sardo, 03163 Venezia (RE)",
        "visibility" => 1,
        "slug" => "voluptate-ea-deleniti-perspiciatis-officiis-sed",
        "longitude" => 129.380139,
        "latitude" => -32.580425,
        "description" => "Provident voluptate sunt rem distinctio praesentium facere. Earum quia eveniet rerum voluptatem est repellat. Aut occaecati ipsum amet nulla natus et odit. Sit molestiae corporis autem.",
        "price" => 390292.0614975933,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/0044ff?text=apartments+ex"
    ],
    [
        "user_id" => 43,
        "title" => "Ullam et quo adipisci repellat quo aut autem.",
        "rooms" => 2,
        "bedrooms" => 1,
        "bathrooms" => 2,
        "square_meters" => 81,
        "address" => "Rotonda Claudia 3 Piano 6\nSartori terme, 15185 Cagliari (SA)",
        "visibility" => 1,
        "slug" => "suscipit-sed-molestiae-qui-iure",
        "longitude" => 164.834996,
        "latitude" => -77.665778,
        "description" => "Iure omnis rerum perspiciatis velit. Molestiae earum consequatur at voluptates quasi. Aspernatur nihil pariatur expedita quam dolore.",
        "price" => 583756.3561805321,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00dd11?text=apartments+illum"
    ],
    [
        "user_id" => 11,
        "title" => "Ut modi dolores dolores repudiandae.",
        "rooms" => 1,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 71,
        "address" => "Contrada Giordano 53 Piano 4\nLoretta sardo, 59122 Vicenza (PT)",
        "visibility" => 0,
        "slug" => "quibusdam-est-reprehenderit-eveniet-minima-qui-nobis-distinctio",
        "longitude" => 29.576808,
        "latitude" => 66.814854,
        "description" => "Totam sit et non quisquam. Et commodi quos rerum blanditiis praesentium. Iure consectetur vero et nam dolor tenetur.",
        "price" => 796810.507903253,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/0055dd?text=apartments+dolorum"
    ],
    [
        "user_id" => 40,
        "title" => "Ut eaque optio qui.",
        "rooms" => 2,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 121,
        "address" => "Piazza Montanari 974 Appartamento 83\nFerrara calabro, 18859 Lecce (ME)",
        "visibility" => 1,
        "slug" => "minus-adipisci-hic-dolorem-porro-eos",
        "longitude" => -14.042079,
        "latitude" => -38.918291,
        "description" => "Et odit velit non quibusdam. Voluptates assumenda nihil omnis praesentium doloremque officia tempora. Ab quos illo et repellat.",
        "price" => 511062.9608347374,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00bb55?text=apartments+ut"
    ],
    [
        "user_id" => 28,
        "title" => "Atque fugiat quia sint quas.",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 88,
        "address" => "Contrada Barone 14 Appartamento 21\nFontana laziale, 74181 Teramo (SI)",
        "visibility" => 0,
        "slug" => "nemo-aut-molestiae-enim-beatae-repudiandae",
        "longitude" => 149.298341,
        "latitude" => 51.330823,
        "description" => "Aut ut in cumque minima quas quia. Maxime corrupti a est atque laudantium doloribus nemo accusantium. Distinctio soluta ut consectetur dolores eius.",
        "price" => 204187.0827061064,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/001144?text=apartments+atque"
    ],
    [
        "user_id" => 47,
        "title" => "Non omnis sunt itaque inventore.",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 61,
        "address" => "Strada Pellegrino 876 Appartamento 52\nCosetta ligure, 82274 Vercelli (CH)",
        "visibility" => 0,
        "slug" => "veniam-alias-quia-nam-dolor-ut-molestiae",
        "longitude" => -9.637507,
        "latitude" => -86.660265,
        "description" => "Impedit libero est architecto totam. Ad officia pariatur sed non inventore. Alias dolorem ex ea ea non minima vero.",
        "price" => 190660.6629493929,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/007733?text=apartments+et"
    ],
    [
        "user_id" => 17,
        "title" => "Nulla numquam ut tempore saepe qui nihil.",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 137,
        "address" => "Incrocio Omar 652 Appartamento 84\nMonti del friuli, 91600 Brescia (IS)",
        "visibility" => 0,
        "slug" => "a-quas-placeat-minima-enim",
        "longitude" => -102.179788,
        "latitude" => 21.095864,
        "description" => "Quidem ex sequi maiores saepe. Optio doloribus ut id qui dolorum.",
        "price" => 912493.2917312222,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00ff44?text=apartments+fugit"
    ],
    [
        "user_id" => 40,
        "title" => "Est voluptatem ea perspiciatis aut occaecati quos non.",
        "rooms" => 1,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 94,
        "address" => "Incrocio Fabbri 34\nJacopo calabro, 64776 Agrigento (RA)",
        "visibility" => 1,
        "slug" => "recusandae-qui-voluptas-qui-et-hic-quidem-quo-dolorum",
        "longitude" => -102.994619,
        "latitude" => -55.982319,
        "description" => "Delectus est odit consequatur reiciendis quis ipsa ut omnis. Ipsam omnis incidunt ipsa nam quam. Reiciendis omnis repellendus sed odio sit quos. Et nesciunt possimus libero enim.",
        "price" => 854229.7954085423,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00ccff?text=apartments+veritatis"
    ],
    [
        "user_id" => 11,
        "title" => "Saepe quia eligendi cum iure odio voluptatem unde.",
        "rooms" => 2,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 172,
        "address" => "Via Sala 1 Appartamento 40\nQuarto Cira ligure, 03360 Varese (SA)",
        "visibility" => 1,
        "slug" => "enim-ad-ut-est-eum-perspiciatis-esse-sed-eos",
        "longitude" => 19.152841,
        "latitude" => -56.079223,
        "description" => "Ex ut molestias perspiciatis. Modi debitis possimus est. Et aut ut maiores molestias. Est enim dolorum qui explicabo inventore maxime. Nesciunt similique quasi voluptatum eum aut.",
        "price" => 978841.7976809861,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/006622?text=apartments+enim"
    ],
    [
        "user_id" => 23,
        "title" => "Minus quasi omnis sunt fugiat quia.",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 108,
        "address" => "Via D'amico 899\nSettimo Ninfa a mare, 92492 Arezzo (RC)",
        "visibility" => 1,
        "slug" => "sequi-exercitationem-deserunt-eaque-quaerat-voluptatem-porro-voluptatem-voluptatibus",
        "longitude" => -31.852729,
        "latitude" => -85.203581,
        "description" => "Vero eos est architecto nemo temporibus dolorem odit. Ut qui ex consequuntur. Et dolores nihil dicta nulla. Veniam nobis aspernatur in laudantium illum aliquid molestiae.",
        "price" => 362318.5384843119,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00ff66?text=apartments+sunt"
    ],
    [
        "user_id" => 43,
        "title" => "Hic molestias aut occaecati.",
        "rooms" => 5,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 197,
        "address" => "Borgo Clea 2 Piano 2\nAntonino salentino, 95174 Benevento (PC)",
        "visibility" => 0,
        "slug" => "qui-eos-iste-iure-architecto",
        "longitude" => 84.650044,
        "latitude" => -17.158031,
        "description" => "Praesentium distinctio voluptatem sunt est velit. Facere explicabo rerum dolor facere. Commodi vel aut natus numquam in sequi. Culpa incidunt vero dolores sunt.",
        "price" => 650683.9194990154,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00dd44?text=apartments+quas"
    ],
    [
        "user_id" => 31,
        "title" => "A voluptatum nihil rerum debitis.",
        "rooms" => 5,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 70,
        "address" => "Strada Cleopatra 38\nSettimo Raniero sardo, 87185 Novara (RN)",
        "visibility" => 0,
        "slug" => "eius-dicta-et-reiciendis-qui-in",
        "longitude" => 122.264893,
        "latitude" => 79.570736,
        "description" => "Pariatur architecto fuga et ex. Blanditiis nobis voluptates accusantium consequatur quo deleniti mollitia illo. Dignissimos soluta nesciunt quia qui fugit tenetur est. Aliquid alias quisquam laborum neque quod iusto nisi.",
        "price" => 132669.94355370753,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/009988?text=apartments+iure"
    ],
    [
        "user_id" => 20,
        "title" => "Cum est provident eos quia.",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 109,
        "address" => "Incrocio Grasso 32\nSesto Mercedes umbro, 29396 Ragusa (VC)",
        "visibility" => 1,
        "slug" => "cupiditate-et-sint-perferendis-sunt",
        "longitude" => -125.63939,
        "latitude" => 61.55705,
        "description" => "Dignissimos eum culpa officia placeat ut labore. Minus id vitae possimus a id. Laboriosam consequatur et qui possimus quaerat dignissimos. Et fuga ea aut asperiores ipsa ad fugiat. At maxime et enim quam aut sapiente non.",
        "price" => 104301.06431446088,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00aa44?text=apartments+voluptatem"
    ],
    [
        "user_id" => 13,
        "title" => "Aut omnis cumque sequi et consectetur voluptates eligendi.",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 101,
        "address" => "Strada Battaglia 9\nGatti calabro, 31102 Medio Campidano (RI)",
        "visibility" => 0,
        "slug" => "eos-enim-aut-et-nihil-debitis-suscipit-eveniet-modi",
        "longitude" => -100.460834,
        "latitude" => -40.772505,
        "description" => "Est aut incidunt ex est atque. Nihil quas eum quaerat praesentium quasi sit qui. Et quia placeat asperiores impedit officia. Dolorum vel nihil necessitatibus aut dolorem eius.",
        "price" => 619729.287167885,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/0033bb?text=apartments+porro"
    ],
    [
        "user_id" => 18,
        "title" => "Reiciendis quam aliquid minima commodi sit vero et.",
        "rooms" => 5,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 150,
        "address" => "Strada Pellegrino 283 Appartamento 89\nLisa calabro, 86792 Padova (OT)",
        "visibility" => 1,
        "slug" => "quidem-repellat-explicabo-ipsa-unde-minima-impedit",
        "longitude" => -29.676266,
        "latitude" => -15.822127,
        "description" => "Sit et voluptas qui nisi sed minima magni. Amet placeat qui atque veritatis voluptatem dolorem. Consectetur reiciendis quia suscipit magni neque perspiciatis. Ratione et dolorem labore odio adipisci consequatur cumque.",
        "price" => 488712.4579766358,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/0055ee?text=apartments+culpa"
    ],
    [
        "user_id" => 38,
        "title" => "Modi officiis quia inventore aut et suscipit.",
        "rooms" => 2,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 117,
        "address" => "Piazza Leone 1 Piano 9\nSesto Isabel, 74894 Cuneo (PO)",
        "visibility" => 0,
        "slug" => "fugit-magnam-dolor-reiciendis-qui",
        "longitude" => -161.799773,
        "latitude" => -48.079935,
        "description" => "Vel quod et tenetur minima. Enim dolor est optio ut qui nemo incidunt. Est aut dolorem fuga. Cumque ad expedita voluptas molestiae sequi est numquam. Sed est veniam consectetur quam mollitia.",
        "price" => 999449.4838916927,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/0033ff?text=apartments+commodi"
    ],
    [
        "user_id" => 35,
        "title" => "Quis dolorem aut iste voluptas esse.",
        "rooms" => 5,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 156,
        "address" => "Strada Valentini 4\nPiersilvio del friuli, 46724 Cuneo (OT)",
        "visibility" => 0,
        "slug" => "veniam-et-sit-debitis-esse",
        "longitude" => -176.154884,
        "latitude" => 49.037301,
        "description" => "Ut debitis est et reiciendis. Aut qui quibusdam ut facilis qui. Est voluptatem odio mollitia ut.",
        "price" => 823267.4716754198,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00cc33?text=apartments+ipsum"
    ],
    [
        "user_id" => 22,
        "title" => "Molestias tempore beatae porro quia aut qui.",
        "rooms" => 4,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 128,
        "address" => "Rotonda Hector 481\nFerrari a mare, 20668 Oristano (PD)",
        "visibility" => 1,
        "slug" => "earum-aut-temporibus-odit-et",
        "longitude" => -19.909563,
        "latitude" => -13.795162,
        "description" => "Vel voluptatem numquam itaque est optio repudiandae non. Quo aut porro rem magnam. Suscipit quaerat at vero quos id quis.",
        "price" => 645898.7527507817,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00ee88?text=apartments+aut"
    ],
    [
        "user_id" => 12,
        "title" => "Porro ipsum ut voluptatem illo optio corporis doloremque.",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 132,
        "address" => "Rotonda Miriana 866 Appartamento 23\nSirio nell'emilia, 45928 Roma (VV)",
        "visibility" => 0,
        "slug" => "et-aut-ipsam-perspiciatis-id",
        "longitude" => 15.861108,
        "latitude" => -23.841515,
        "description" => "Velit soluta et qui eum. Animi doloremque amet dolorum. Qui unde quia ad eum sint error. Esse qui tempore illo est nulla magnam officiis. Vel quibusdam pariatur molestias sunt magni.",
        "price" => 268394.0214050906,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/009955?text=apartments+aut"
    ],
    [
        "user_id" => 48,
        "title" => "Mollitia atque reprehenderit consequuntur eum quisquam eveniet deserunt.",
        "rooms" => 3,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 119,
        "address" => "Piazza Adriano 307\nPellegrino veneto, 04090 La Spezia (BI)",
        "visibility" => 0,
        "slug" => "qui-ipsa-id-omnis-dignissimos",
        "longitude" => 171.679232,
        "latitude" => -33.687831,
        "description" => "Nesciunt esse eius quidem quidem eligendi dolorum. Rerum aut sunt alias quos quos quia soluta ad.",
        "price" => 763899.8345816041,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/0000ee?text=apartments+eius"
    ],
    [
        "user_id" => 47,
        "title" => "Tenetur aut doloremque est sunt aperiam velit.",
        "rooms" => 3,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 128,
        "address" => "Rotonda Tancredi 87 Appartamento 58\nRinaldi nell'emilia, 82574 Latina (TR)",
        "visibility" => 0,
        "slug" => "consequatur-rerum-aut-omnis-nemo",
        "longitude" => 27.416815,
        "latitude" => -8.729172,
        "description" => "Deleniti et enim expedita natus dicta nihil omnis. Nobis dolores veritatis laudantium corporis. Maxime et et iste ad consequuntur quos laboriosam. Rem reprehenderit velit dolore quia vel porro libero nemo. Aut veritatis id cumque.",
        "price" => 511345.99788177107,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00cc55?text=apartments+omnis"
    ],
    [
        "user_id" => 6,
        "title" => "Aperiam perspiciatis qui suscipit aut nisi inventore delectus.",
        "rooms" => 1,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 51,
        "address" => "Incrocio Fernando 34\nOrtensia nell'emilia, 77892 Belluno (GE)",
        "visibility" => 0,
        "slug" => "nostrum-accusantium-iure-minima-et-praesentium-voluptatibus",
        "longitude" => 147.287666,
        "latitude" => -0.72831,
        "description" => "Et eum magnam architecto dolorem. Quibusdam suscipit dolores laboriosam nihil at. Excepturi magni quo dolor libero. Cumque omnis unde dolorum consequatur non enim in.",
        "price" => 924085.269488434,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00dd11?text=apartments+consequatur"
    ],
    [
        "user_id" => 14,
        "title" => "Nihil ut dolorem qui itaque in ut.",
        "rooms" => 5,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 95,
        "address" => "Borgo Bacchisio 61 Piano 9\nSan Joey, 14129 Biella (OR)",
        "visibility" => 1,
        "slug" => "velit-consequatur-laborum-sit-numquam-et-nostrum-aut",
        "longitude" => -40.022229,
        "latitude" => -6.084489,
        "description" => "Dignissimos maxime accusantium minus sunt dolores ut. Vero excepturi officiis commodi voluptas quia nostrum. Et quasi dolorem dolor magni et molestiae eaque.",
        "price" => 497408.0775153861,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00aa11?text=apartments+velit"
    ],
    [
        "user_id" => 38,
        "title" => "Ducimus animi nam qui architecto nostrum.",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 196,
        "address" => "Incrocio Ileana 55 Appartamento 20\nSan Alberto, 77066 Caserta (AN)",
        "visibility" => 1,
        "slug" => "id-quis-excepturi-nostrum-eaque-repudiandae",
        "longitude" => -129.799236,
        "latitude" => -39.22308,
        "description" => "Repellat voluptates eum temporibus facilis impedit sit. Corporis voluptatibus magni ut. Omnis est laboriosam incidunt blanditiis architecto.",
        "price" => 277072.0886518583,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/0044bb?text=apartments+aliquam"
    ],
    [
        "user_id" => 28,
        "title" => "Dolorem sint est sint aut voluptas adipisci.",
        "rooms" => 1,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 95,
        "address" => "Incrocio Moretti 1 Appartamento 01\nSesto Samira, 86412 Siena (VC)",
        "visibility" => 1,
        "slug" => "in-est-delectus-culpa-pariatur-officia-nemo-reprehenderit",
        "longitude" => -127.803153,
        "latitude" => -75.014053,
        "description" => "Nostrum corporis quo quaerat minus. Ipsum dicta at debitis et sit id. Molestias sed sit beatae aut iure accusantium. Nesciunt at nam reprehenderit quos ducimus iure tempora.",
        "price" => 510611.2537023664,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00ffee?text=apartments+laborum"
    ],
    [
        "user_id" => 34,
        "title" => "Ab consequatur velit qui autem.",
        "rooms" => 3,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 174,
        "address" => "Borgo Siro 971 Appartamento 94\nQuarto Fulvio, 73559 Viterbo (PU)",
        "visibility" => 0,
        "slug" => "ut-quis-ipsam-blanditiis-fugit-neque",
        "longitude" => 88.29448,
        "latitude" => -85.979675,
        "description" => "Qui excepturi iusto nulla delectus alias quia. Cumque dolorum in vel sed aperiam. Dolor qui maxime accusamus tempora labore placeat.",
        "price" => 962564.4357933498,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00bb88?text=apartments+distinctio"
    ],
    [
        "user_id" => 44,
        "title" => "Odio quas animi quis velit.",
        "rooms" => 2,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 172,
        "address" => "Strada Martinelli 424\nMuzio sardo, 37725 Benevento (PV)",
        "visibility" => 1,
        "slug" => "necessitatibus-rerum-porro-impedit-doloribus-veritatis-earum-laboriosam-ullam",
        "longitude" => 140.747645,
        "latitude" => 53.534841,
        "description" => "Ut iusto necessitatibus corporis est beatae suscipit consequatur at. Tenetur velit tempora voluptatem nostrum rerum. Eos nostrum facilis quod molestiae.",
        "price" => 972156.4074662311,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/0044cc?text=apartments+reiciendis"
    ],
    [
        "user_id" => 46,
        "title" => "Tenetur quos amet consequatur fugit itaque nihil possimus.",
        "rooms" => 3,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 176,
        "address" => "Rotonda Pellegrino 93\nBorgo Mariano lido, 44596 Macerata (MT)",
        "visibility" => 0,
        "slug" => "nemo-ipsa-exercitationem-fugiat-facilis-ut-numquam-et",
        "longitude" => -47.717734,
        "latitude" => -11.925305,
        "description" => "Ad cum rerum sed sint vel autem eos et. Est ipsam possimus tempora ipsam qui. Facilis et ipsa placeat.",
        "price" => 104657.89530177503,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/0022dd?text=apartments+at"
    ],
    [
        "user_id" => 32,
        "title" => "Unde nulla voluptatem non deleniti dolorem sunt dolores quo.",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 200,
        "address" => "Rotonda Ricci 606\nGenziana umbro, 41178 Bergamo (TE)",
        "visibility" => 0,
        "slug" => "vel-reprehenderit-quia-soluta-quisquam",
        "longitude" => 107.143184,
        "latitude" => -65.334232,
        "description" => "Repellat quam ex accusantium fugit quidem suscipit ab natus. Dolor consequatur est facere architecto. Id velit libero dolorem quaerat nihil ea veniam.",
        "price" => 175239.83115108675,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00eeff?text=apartments+facere"
    ],
    [
        "user_id" => 14,
        "title" => "Eligendi sit ea est ut.",
        "rooms" => 3,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 65,
        "address" => "Borgo Jelena 69 Appartamento 85\nQuarto Ursula, 19124 Viterbo (VA)",
        "visibility" => 1,
        "slug" => "praesentium-autem-velit-commodi",
        "longitude" => -79.530826,
        "latitude" => -17.849932,
        "description" => "Voluptatem reprehenderit eius voluptas qui ut impedit dolores. Perspiciatis assumenda ut beatae modi. Veritatis doloribus qui possimus molestias sit asperiores nam.",
        "price" => 482841.7971743465,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/00ff88?text=apartments+qui"
    ],
    [
        "user_id" => 49,
        "title" => "Dolores ex enim nihil ullam vel.",
        "rooms" => 5,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 136,
        "address" => "Via Sala 13 Piano 7\nSettimo Tosca, 81131 Messina (BG)",
        "visibility" => 1,
        "slug" => "dicta-pariatur-ut-provident-odit-consequuntur-eius-voluptatem",
        "longitude" => -51.954328,
        "latitude" => 0.244157,
        "description" => "Rem ipsum aut pariatur voluptatum consectetur unde est dolor. Earum cumque quo harum. Corrupti et sit sit cum et.",
        "price" => 638576.1816979274,
        "cover" => "https:\/\/via.placeholder.com\/640x480.png\/004422?text=apartments+nesciunt"
    ]
];