<?php

return [
    [
        "user_id" => 1,
        "title" => "Appartamento moderno con vista panoramica",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 139,
        "address" => "Rotonda Ciro Menotti, 41122 Modena",
        "visibility" => 1,
        "slug" => "voluptatem-eum-id-excepturi-officia-at-et",
        "longitude" => 10.9392,
        "latitude" => 44.64949,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 6000,
        "cover" => "https://live.staticflickr.com/65535/53076672522_44321178fb_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Accogliente monolocale nel cuore della città",
        "rooms" => 3,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 146,
        "address" => "Via San Daniele del Friuli, 33037 Pasian di Prato",
        "visibility" => 1,
        "slug" => "itaque-magni-autem-occaecati-omnis",
        "longitude" => 13.18579,
        "latitude" => 46.07888,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 5800,
        "cover" => "https://live.staticflickr.com/65535/53076672552_ebf0acfffb_h.jpg",
        "vote" => 4
    ],
    [
        "user_id" => 1,
        "title" => "Spazioso trilocale con giardino privato",
        "rooms" => 4,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 176,
        "address" => "Via Varese, Bardello con Malgesso e Bregano",
        "visibility" => 0,
        "slug" => "autem-accusantium-quo-nam-et-repellendus-in",
        "longitude" => 8.67774,
        "latitude" => 45.83019,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 29000,
        "cover" => "https://live.staticflickr.com/65535/53076672552_ebf0acfffb_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Attico di lusso con terrazza panoramica",
        "rooms" => 4,
        "bedrooms" => 1,
        "bathrooms" => 2,
        "square_meters" => 151,
        "address" => "Poderi Via Napoli, Foggia",
        "visibility" => 0,
        "slug" => "occaecati-est-nostrum-non-voluptatem-occaecati",
        "longitude" => 15.49487,
        "latitude" => 41.43048,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 359000,
        "cover" => "https://live.staticflickr.com/65535/53077744048_cc0f08f157_h.jpg",
        "vote" => 5
    ],
    [
        "user_id" => 1,
        "title" => "Monolocale elegante nel centro storico",
        "rooms" => 2,
        "bedrooms" => 1,
        "bathrooms" => 2,
        "square_meters" => 168,
        "address" => "Via Agrigento, 73040 Collepasso",
        "visibility" => 1,
        "slug" => "neque-ut-sed-earum",
        "longitude" => 18.16093,
        "latitude" => 40.07555,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 33800,
        "cover" => "https://live.staticflickr.com/65535/53076672582_971f6341ae_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento luminoso e completamente ristrutturato",
        "rooms" => 4,
        "bedrooms" => 1,
        "bathrooms" => 2,
        "square_meters" => 137,
        "address" => "Roma, Borgo Mantovano",
        "visibility" => 0,
        "slug" => "quo-et-ut-et-molestias-eos-quis-occaecati-error",
        "longitude" => 11.10728,
        "latitude" => 44.99401,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 96000,
        "cover" => "https://live.staticflickr.com/65535/53077244956_097408140b_h.jpg",
        "vote" => 4
    ],
    [
        "user_id" => 1,
        "title" => "Quadrilocale con piscina e area barbecue",
        "rooms" => 3,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 173,
        "address" => "Bagni di Lucca",
        "visibility" => 0,
        "slug" => "cupiditate-repellendus-quod-vel-dolores-eos",
        "longitude" => 10.59078,
        "latitude" => 44.01195,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 497000,
        "cover" => "https://live.staticflickr.com/65535/53077440994_990cb73dd5_h.jpg",
        "vote" => 5
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento al mare con vista mozzafiato",
        "rooms" => 2,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 84,
        "address" => "Via Brescia, Conza della Campania",
        "visibility" => 0,
        "slug" => "aut-unde-omnis-maiores-incidunt",
        "longitude" => 15.30552,
        "latitude" => 40.87153,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 792747.33,
        "cover" => "https://live.staticflickr.com/65535/53077744428_cfc0219581_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Loft moderno con dettagli di design",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 72,
        "address" => "Via Brescia, Sella Giudicarie",
        "visibility" => 1,
        "slug" => "vel-et-qui-impedit-suscipit",
        "longitude" => 10.6618,
        "latitude" => 45.97035,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 31600,
        "cover" => "https://live.staticflickr.com/65535/53076672677_47e63079dd_h.jpg",
        "vote" => 4
    ],
    [
        "user_id" => 1,
        "title" => "Bilocale con balcone e vista sul parco",
        "rooms" => 1,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 65,
        "address" => "Via Bergamo, Roma",
        "visibility" => 0,
        "slug" => "fugiat-nisi-omnis-reprehenderit",
        "longitude" => 12.50001,
        "latitude" => 41.91124,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 663000,
        "cover" => "https://live.staticflickr.com/65535/53076672692_33cea285de_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento d'epoca con soffitti alti",
        "rooms" => 2,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 135,
        "address" => "Baglio Messina Primo, Custonaci",
        "visibility" => 0,
        "slug" => "atque-dolorem-consequatur-blanditiis-et-officia",
        "longitude" => 12.70144,
        "latitude" => 38.07707,
        "description" => '',
        "price" => 114000,
        "cover" => "https://live.staticflickr.com/65535/53077441089_d0d1ec5dc7_h.jpg",
        "vote" => 5
    ],
    [
        "user_id" => 1,
        "title" => "Elegante appartamento con caminetto",
        "rooms" => 5,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 151,
        "address" => "Strada Serreta-Imperia, Diano Marina",
        "visibility" => 1,
        "slug" => "similique-odit-libero-voluptatem-et",
        "longitude" => 8.0551,
        "latitude" => 43.91322,
        "description" => '',
        "price" => 73900,
        "cover" => "https://live.staticflickr.com/65535/53077744458_cf94c239bb_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Ampio trilocale con spaziosa cucina abitabile",
        "rooms" => 4,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 93,
        "address" => "Venezia Sestiere Castello, Venezia",
        "visibility" => 1,
        "slug" => "aut-odit-voluptatem-sapiente-aut-necessitatibus",
        "longitude" => 12.34515,
        "latitude" => 45.43843,
        "description" => '',
        "price" => 61800,
        "cover" => "https://live.staticflickr.com/65535/53077655145_170ac4f6c4_h.jpg",
        "vote" => 4
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento di charme in palazzo storico",
        "rooms" => 4,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 78,
        "address" => "Marina di Ravenna, Ravenna",
        "visibility" => 0,
        "slug" => "cumque-commodi-exercitationem-repudiandae-eaque-commodi",
        "longitude" => 12.27858,
        "latitude" => 44.48675,
        "description" => '',
        "price" => 83000,
        "cover" => "https://live.staticflickr.com/65535/53077245066_fc1857c0d4_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Monolocale con accesso alla piscina condominiale",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 90,
        "address" => "Via Mantova, Mantova",
        "visibility" => 1,
        "slug" => "cum-ipsa-voluptas-deserunt-aut-autem-modi-aspernatur",
        "longitude" => 12.6646,
        "latitude" => 45.85972,
        "description" => '',
        "price" => 112432.95,
        "cover" => "https://live.staticflickr.com/65535/53076673232_43c6d122d2_h.jpg",
        "vote" => 4
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento vicino al centro commerciale",
        "rooms" => 4,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 143,
        "address" => "Via Avellino, 00176 Roma",
        "visibility" => 1,
        "slug" => "molestiae-quam-magni-est-quas-est-esse",
        "longitude" => 12.5261,
        "latitude" => 41.88786,
        "description" => '',
        "price" => 706000,
        "cover" => "https://live.staticflickr.com/65535/53077441159_230dc495d4_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Loft industriale con dettagli in mattoni a vista",
        "rooms" => 2,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 75,
        "address" => "Viale Ogliastra, Lanusei",
        "visibility" => 0,
        "slug" => "a-fugiat-eaque-nemo-quos-consequatur-est-et",
        "longitude" => 9.5488,
        "latitude" => 39.87851,
        "description" => '',
        "price" => 52000,
        "cover" => "https://live.staticflickr.com/65535/53077655190_2bc8ca7ca0_h.jpg",
        "vote" => 5
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento panoramico con vista mare",
        "rooms" => 1,
        "bedrooms" => 1,
        "bathrooms" => 2,
        "square_meters" => 199,
        "address" => "Barletta-Andria-Trani",
        "visibility" => 0,
        "slug" => "nihil-qui-inventore-repellat-repellat-repellat-fugit",
        "longitude" => 16.17096,
        "latitude" => 41.17281,
        "description" => '',
        "price" => 71000,
        "cover" => "https://live.staticflickr.com/65535/53077245096_84889a437c_h.jpg",
        "vote" => 4
    ],
    [
        "user_id" => 1,
        "title" => "Trilocale arredato con gusto",
        "rooms" => 3,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 66,
        "address" => "Via M. Bianchi, 85030 San Paolo Albanese",
        "visibility" => 1,
        "slug" => "cupiditate-quos-libero-et-dolorem-voluptatibus-aperiam",
        "longitude" => 16.3355,
        "latitude" => 40.03553,
        "description" => '',
        "price" => 42000,
        "cover" => "https://live.staticflickr.com/65535/53077441244_077899fadb_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento con camino e terrazzo privato",
        "rooms" => 3,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 147,
        "address" => "Strada Seconda Rotonda, Vietri di Potenza",
        "visibility" => 1,
        "slug" => "voluptate-ea-deleniti-perspiciatis-officiis-sed",
        "longitude" => 15.55529,
        "latitude" => 40.6311,
        "description" => '',
        "price" => 39000,
        "cover" => "https://live.staticflickr.com/65535/53077441464_acc5e15937_h.jpg",
        "vote" => 5
    ],
    [
        "user_id" => 1,
        "title" => "Delizioso bilocale in zona tranquilla",
        "rooms" => 2,
        "bedrooms" => 1,
        "bathrooms" => 2,
        "square_meters" => 81,
        "address" => "Via Cagliari, Palazzolo sull'Oglio",
        "visibility" => 1,
        "slug" => "suscipit-sed-molestiae-qui-iure",
        "longitude" => 9.91587,
        "latitude" => 45.60734,
        "description" => '',
        "price" => 58000,
        "cover" => "https://live.staticflickr.com/65535/53077244626_0892274a77_h.jpg",
        "vote" => 5
    ],
    [
        "user_id" => 1,
        "title" => "Attico con vista sulla città e terrazza privata",
        "rooms" => 1,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 71,
        "address" => "Via Vicenza, Piove di Sacco",
        "visibility" => 0,
        "slug" => "quibusdam-est-reprehenderit-eveniet-minima-qui-nobis-distinctio",
        "longitude" => 12.10192,
        "latitude" => 45.29833,
        "description" => '',
        "price" => 79000,
        "cover" => "https://live.staticflickr.com/65535/53076673122_0443448876_h.jpg",
        "vote" => 4
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento ristrutturato in stile moderno",
        "rooms" => 2,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 121,
        "address" => "Via Cumbito Lecce Vecchio, 67050 Lecce nei Marsi",
        "visibility" => 1,
        "slug" => "minus-adipisci-hic-dolorem-porro-eos",
        "longitude" => 13.67253,
        "latitude" => 41.91658,
        "description" => '',
        "price" => 51000,
        "cover" => "https://live.staticflickr.com/65535/53076673187_36270849b8_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Ampio quadrilocale con parcheggio interno",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 88,
        "address" => "Via Teramo, 64046 Montorio al Vomano",
        "visibility" => 0,
        "slug" => "nemo-aut-molestiae-enim-beatae-repudiandae",
        "longitude" => 13.62252,
        "latitude" => 42.58237,
        "description" => '',
        "price" => 20000,
        "cover" => "https://live.staticflickr.com/65535/53077655530_fc80856c48_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento con giardino e spazio barbecue",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 61,
        "address" => "Via Vercelli, Vercelli",
        "visibility" => 0,
        "slug" => "veniam-alias-quia-nam-dolor-ut-molestiae",
        "longitude" => 9.46452,
        "latitude" => 41.04567,
        "description" => '',
        "price" => 19000,
        "cover" => "https://live.staticflickr.com/65535/53077441544_322bf153c2_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Monolocale con cucina a vista",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 137,
        "address" => "Via Brescia, Conza della Campania",
        "visibility" => 0,
        "slug" => "a-quas-placeat-minima-enim",
        "longitude" => 15.30552,
        "latitude" => 40.87153,
        "description" => '',
        "price" => 91000,
        "cover" => "https://live.staticflickr.com/65535/53076673272_e2373e4a01_h.jpg",
        "vote" => 4
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento luminoso con ampie finestre",
        "rooms" => 1,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 94,
        "address" => "Via Agrigento, 73040 Collepasso",
        "visibility" => 1,
        "slug" => "recusandae-qui-voluptas-qui-et-hic-quidem-quo-dolorum",
        "longitude" => 18.16093,
        "latitude" => 40.07555,
        "description" => '',
        "price" => 85000,
        "cover" => "https://live.staticflickr.com/65535/53077441594_a78299a66f_h.jpg",
        "vote" => 5
    ],
    [
        "user_id" => 1,
        "title" => "Bilocale con accesso alla piscina condominiale",
        "rooms" => 2,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 172,
        "address" => "San Varese, Torre d'Isola",
        "visibility" => 1,
        "slug" => "enim-ad-ut-est-eum-perspiciatis-esse-sed-eos",
        "longitude" => 9.05008,
        "latitude" => 45.23572,
        "description" => '',
        "price" => 97000,
        "cover" => "https://live.staticflickr.com/65535/53077441604_29f7be428e_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento in zona residenziale e silenziosa",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 108,
        "address" => "Via Arezzo, 25125 Brescia",
        "visibility" => 1,
        "slug" => "sequi-exercitationem-deserunt-eaque-quaerat-voluptatem-porro-voluptatem-voluptatibus",
        "longitude" => 10.18665,
        "latitude" => 45.52817,
        "description" => '',
        "price" => 36000,
        "cover" => "https://live.staticflickr.com/65535/53076673297_9ef174df7f_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Loft con soppalco e design contemporaneo",
        "rooms" => 5,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 197,
        "address" => "Via Benevento, 82025 Montefalcone di Val Fortore",
        "visibility" => 0,
        "slug" => "qui-eos-iste-iure-architecto",
        "longitude" => 15.00637,
        "latitude" => 41.32231,
        "description" => '',
        "price" => 650683.91,
        "cover" => "https://live.staticflickr.com/65535/53076673347_e55d49620a_h.jpg",
        "vote" => 5
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento in palazzo d'epoca con affreschi",
        "rooms" => 5,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 70,
        "address" => "Via Novara, 47814 Bellaria-Igea Marina",
        "visibility" => 0,
        "slug" => "eius-dicta-et-reiciendis-qui-in",
        "longitude" => 12.44851,
        "latitude" => 44.15623,
        "description" => '',
        "price" => 130000,
        "cover" => "https://live.staticflickr.com/65535/53076673372_03f0c5bb8e_h.jpg",
        "vote" => 5
    ],
    [
        "user_id" => 1,
        "title" => "Trilocale con terrazzo e vista sulle montagne",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 109,
        "address" => "Circonvallazione Ragusa & Via Vincenzo Cerulli Irelli, 64100 Teramo",
        "visibility" => 1,
        "slug" => "cupiditate-et-sint-perferendis-sunt",
        "longitude" => 13.70066,
        "latitude" => 42.66219,
        "description" => '',
        "price" => 10000,
        "cover" => "https://live.staticflickr.com/65535/53077245681_c4e9eb0d3f_h.jpg",
        "vote" => 4
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento in residence con servizi inclusi",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 101,
        "address" => "Via Campidano, 35142 Padova",
        "visibility" => 0,
        "slug" => "eos-enim-aut-et-nihil-debitis-suscipit-eveniet-modi",
        "longitude" => 11.85184,
        "latitude" => 45.38398,
        "description" => '',
        "price" => 61000,
        "cover" => "https://live.staticflickr.com/65535/53077745253_a8dd14acef_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Monolocale in zona ben servita dai mezzi pubblici",
        "rooms" => 5,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 150,
        "address" => "Strada Provinciale di San Pellegrino in Alpe, 55033 Castiglione di Garfagnana",
        "visibility" => 1,
        "slug" => "quidem-repellat-explicabo-ipsa-unde-minima-impedit",
        "longitude" => 10.43608,
        "latitude" => 44.1459,
        "description" => '',
        "price" => 48000,
        "cover" => "https://live.staticflickr.com/65535/53077245821_10ab8b8155_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento con vista sulla campagna circostante",
        "rooms" => 2,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 117,
        "address" => "Borgata Campo, 12025 Montemale di Cuneo",
        "visibility" => 0,
        "slug" => "fugit-magnam-dolor-reiciendis-qui",
        "longitude" => 7.37695,
        "latitude" => 44.43282,
        "description" => '',
        "price" => 99000,
        "cover" => "https://live.staticflickr.com/65535/53077655800_0c70306f19_h.jpg",
        "vote" => 5
    ],
    [
        "user_id" => 1,
        "title" => "Bilocali completamente arredati e attrezzati",
        "rooms" => 5,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 156,
        "address" => "Via Caserta & Via Cuneo, 53045 Montepulciano",
        "visibility" => 0,
        "slug" => "veniam-et-sit-debitis-esse",
        "longitude" => 11.85423,
        "latitude" => 43.13327,
        "description" => '',
        "price" => 82000,
        "cover" => "https://live.staticflickr.com/65535/53077655840_c21ec97673_h.jpg",
        "vote" => 4
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento con cucina spaziosa e moderna",
        "rooms" => 4,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 128,
        "address" => "Viale Oristano, 47838 Riccione",
        "visibility" => 1,
        "slug" => "earum-aut-temporibus-odit-et",
        "longitude" => 12.65402,
        "latitude" => 43.9917,
        "description" => '',
        "price" => 64500,
        "cover" => "https://live.staticflickr.com/65535/53077745323_585025ca94_h.jpg",
        "vote" => 5
    ],
    [
        "user_id" => 1,
        "title" => "Loft con aria condizionata e ampio spazio living",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 132,
        "address" => "Via Genzano di Roma, 00040 Ardea",
        "visibility" => 0,
        "slug" => "et-aut-ipsam-perspiciatis-id",
        "longitude" => 12.6094,
        "latitude" => 41.67509,
        "description" => '',
        "price" => 26000,
        "cover" => "https://live.staticflickr.com/65535/53077745338_e31a044a97_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento con garage e parcheggio privato",
        "rooms" => 3,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 119,
        "address" => "Via Vittorio Veneto & Piazza Dante Alighieri, 19125 La Spezia",
        "visibility" => 0,
        "slug" => "qui-ipsa-id-omnis-dignissimos",
        "longitude" => 9.83674,
        "latitude" => 44.1151,
        "description" => '',
        "price" => 763000,
        "cover" => "https://live.staticflickr.com/65535/53077245896_366c9e65be_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Trilocale con accesso a piscina e palestra",
        "rooms" => 3,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 128,
        "address" => "Marina di Latina, Latina",
        "visibility" => 0,
        "slug" => "consequatur-rerum-aut-omnis-nemo",
        "longitude" => 12.84952,
        "latitude" => 41.41699,
        "description" => '',
        "price" => 51100,
        "cover" => "https://live.staticflickr.com/65535/53077245911_2d7d9aeab1_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento vicino alle principali attrazioni turistiche",
        "rooms" => 1,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 51,
        "address" => "Belluno Veronese, Brentino Belluno",
        "visibility" => 0,
        "slug" => "nostrum-accusantium-iure-minima-et-praesentium-voluptatibus",
        "longitude" => 10.89952,
        "latitude" => 45.68804,
        "description" => '',
        "price" => 92400,
        "cover" => "https://live.staticflickr.com/65535/53077745373_0a8db65184_h.jpg",
        "vote" => 5
    ],
    [
        "user_id" => 1,
        "title" => "Bilocale con terrazza e vista sul lago",
        "rooms" => 5,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 95,
        "address" => "Via Biella, Savignano sul Panaro",
        "visibility" => 1,
        "slug" => "velit-consequatur-laborum-sit-numquam-et-nostrum-aut",
        "longitude" => 10.99435,
        "latitude" => 44.45685,
        "description" => '',
        "price" => 49000,
        "cover" => "https://live.staticflickr.com/65535/53077441899_b68a681fef_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento in condominio con servizio di portineria",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 196,
        "address" => "Portico di Caserta, Macerata Campania",
        "visibility" => 1,
        "slug" => "id-quis-excepturi-nostrum-eaque-repudiandae",
        "longitude" => 14.28918,
        "latitude" => 41.05034,
        "description" => '',
        "price" => 27000,
        "cover" => "https://live.staticflickr.com/65535/53077655930_5177684394_h.jpg",
        "vote" => 4
    ],
    [
        "user_id" => 1,
        "title" => "Loft con cucina a isola e finiture di lusso",
        "rooms" => 1,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 95,
        "address" => "Via Siena, San Benedetto dei Marsi",
        "visibility" => 1,
        "slug" => "in-est-delectus-culpa-pariatur-officia-nemo-reprehenderit",
        "longitude" => 13.61788,
        "latitude" => 42.00374,
        "description" => '',
        "price" => 51000,
        "cover" => "https://live.staticflickr.com/65535/53077655940_4d843d5ce9_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento con camino e pavimenti in parquet",
        "rooms" => 3,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 174,
        "address" => "Bagni di Viterbo, Viterbo",
        "visibility" => 0,
        "slug" => "ut-quis-ipsam-blanditiis-fugit-neque",
        "longitude" => 12.06565,
        "latitude" => 42.41485,
        "description" => '',
        "price" => 96000,
        "cover" => "https://live.staticflickr.com/65535/53077745508_a8b2757b5a_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Monolocale con angolo cottura e bagno privato",
        "rooms" => 2,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 172,
        "address" => "Via Benevento, 82025 Montefalcone di Val Fortore",
        "visibility" => 1,
        "slug" => "necessitatibus-rerum-porro-impedit-doloribus-veritatis-earum-laboriosam-ullam",
        "longitude" => 15.00637,
        "latitude" => 41.32231,
        "description" => '',
        "price" => 97000,
        "cover" => "https://live.staticflickr.com/65535/53077745473_271a1255c6_h.jpg",
        "vote" => 5
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento con vista sul fiume e balcone",
        "rooms" => 3,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 176,
        "address" => "Macerata Campania, Curti",
        "visibility" => 0,
        "slug" => "nemo-ipsa-exercitationem-fugiat-facilis-ut-numquam-et",
        "longitude" => 14.28146,
        "latitude" => 41.06754,
        "description" => '',
        "price" => 10400,
        "cover" => "https://live.staticflickr.com/65535/53077656025_582cb244de_h.jpg",
        "vote" => 4
    ],
    [
        "user_id" => 1,
        "title" => "Trilocale con spazio esterno e area relax",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 200,
        "address" => "Via Don Luigi Palazzolo, 24122 Bergamo",
        "visibility" => 0,
        "slug" => "vel-reprehenderit-quia-soluta-quisquam",
        "longitude" => 9.66547,
        "latitude" => 45.68978,
        "description" => '',
        "price" => 17500,
        "cover" => "https://live.staticflickr.com/65535/53077135516_67459292a2_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento arredato con mobili di design",
        "rooms" => 3,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 65,
        "address" => "Strada Viterbo, Vetralla",
        "visibility" => 1,
        "slug" => "praesentium-autem-velit-commodi",
        "longitude" => 12.08627,
        "latitude" => 42.33442,
        "description" => '',
        "price" => 48200,
        "cover" => "https://live.staticflickr.com/65535/53077330079_a668e0145f_h.jpg",
        "vote" => 3
    ],
    [
        "user_id" => 1,
        "title" => "Loft con soppalco e grandi finestre panoramiche",
        "rooms" => 5,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 136,
        "address" => "Via Lungomare in Piano Torre, 98100 Messina",
        "visibility" => 1,
        "slug" => "dicta-pariatur-ut-provident-odit-consequuntur-eius-voluptatem",
        "longitude" => 15.51272,
        "latitude" => 38.29224,
        "description" => '',
        "price" => 63800,
        "cover" => "https://live.staticflickr.com/65535/53077135481_9d42c3023a_h.jpg",
        "vote" => 3
    ]
];