<?php

return [
    [
        "user_id" => 1,
        "title" => "Appartamento moderno con vista panoramica",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 139,
        "address" => "Rotonda Tancredi 60 Appartamento 29\nClaudia calabro, 17924 Modena (CT)",
        "visibility" => 1,
        "slug" => "voluptatem-eum-id-excepturi-officia-at-et",
        "longitude" => 158.976775,
        "latitude" => 82.028437,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 607814.56,
        "cover" => "https://conciliumtrento.it/wp-content/uploads/2019/05/IMG_4442_3_4_5_6pmx.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Accogliente monolocale nel cuore della città",
        "rooms" => 3,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 146,
        "address" => "Via Karim 492\nIvonne del friuli, 99153 Prato (VS)",
        "visibility" => 1,
        "slug" => "itaque-magni-autem-occaecati-omnis",
        "longitude" => -71.672535,
        "latitude" => -13.343564,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 58250.22,
        "cover" => "https://www.ahtorino.com/public/foto/z1ahtorino-hotel-appartamento-deluxe-salotto.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Spazioso trilocale con giardino privato",
        "rooms" => 4,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 176,
        "address" => "Strada Guerra 12 Piano 8\nSesto Monia sardo, 45049 Varese (AQ)",
        "visibility" => 0,
        "slug" => "autem-accusantium-quo-nam-et-repellendus-in",
        "longitude" => -112.468332,
        "latitude" => 52.696017,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 292753.48,
        "cover" => "https://media-cdn.tripadvisor.com/media/photo-m/1280/17/31/31/a6/appartamenti-astra.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Attico di lusso con terrazza panoramica",
        "rooms" => 4,
        "bedrooms" => 1,
        "bathrooms" => 2,
        "square_meters" => 151,
        "address" => "Strada Basile 553 Piano 4\nDonati lido, 51286 Napoli (RC)",
        "visibility" => 0,
        "slug" => "occaecati-est-nostrum-non-voluptatem-occaecati",
        "longitude" => 15.949334,
        "latitude" => 13.087353,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 359005.84,
        "cover" => "https://media-assets.ad-italia.it/photos/626bd6c4a64dbe59d264a2d0/master/w_1600%2Cc_limit/HOME.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Monolocale elegante nel centro storico",
        "rooms" => 2,
        "bedrooms" => 1,
        "bathrooms" => 2,
        "square_meters" => 168,
        "address" => "Contrada De rosa 1 Piano 6\nSan Joshua, 70878 Agrigento (LU)",
        "visibility" => 1,
        "slug" => "neque-ut-sed-earum",
        "longitude" => 158.974908,
        "latitude" => 76.402409,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 338227.36,
        "cover" => "https://www.garnilagonembia.com/images/_gallery%20divise/04_formula%20appartamento/bilocale/salotto_bilo.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento luminoso e completamente ristrutturato",
        "rooms" => 4,
        "bedrooms" => 1,
        "bathrooms" => 2,
        "square_meters" => 137,
        "address" => "Contrada Rizzo 77 Piano 5\nColombo umbro, 18249 Gorizia (MT)",
        "visibility" => 0,
        "slug" => "quo-et-ut-et-molestias-eos-quis-occaecati-error",
        "longitude" => -176.531972,
        "latitude" => -33.107962,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 965248.16,
        "cover" => "https://cdn.discordapp.com/attachments/1127889223098314815/1134034042807930970/mobile-tv-1.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Quadrilocale con piscina e area barbecue",
        "rooms" => 3,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 173,
        "address" => "Strada Russo 4\nBorgo Grazia calabro, 90884 Lucca (CN)",
        "visibility" => 0,
        "slug" => "cupiditate-repellendus-quod-vel-dolores-eos",
        "longitude" => 85.578065,
        "latitude" => -64.025144,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 497010.49,
        "cover" => "https://www.forma-luxuryliving.com/wp-content/uploads/2023/02/appartamento-ristrutturato.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento al mare con vista mozzafiato",
        "rooms" => 2,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 84,
        "address" => "Via Marianita 452\nQuarto Max calabro, 61602 Brescia (RC)",
        "visibility" => 0,
        "slug" => "aut-unde-omnis-maiores-incidunt",
        "longitude" => -128.583175,
        "latitude" => 9.697423,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 792747.33,
        "cover" => "https://www.viagginewyork.it/wp-content/uploads/2018/01/appartamenti-newyork2.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Loft moderno con dettagli di design",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 72,
        "address" => "Rotonda Danthon 5\nRadio veneto, 34124 Gorizia (BR)",
        "visibility" => 1,
        "slug" => "vel-et-qui-impedit-suscipit",
        "longitude" => -114.179802,
        "latitude" => -1.443268,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 31676.06,
        "cover" => "https://www.john-taylor.it/vendita-appartamento-milano-680x400-80-V1643MI-115894163.jpg?datetime=2023-07-21_1"
    ],
    [
        "user_id" => 1,
        "title" => "Bilocale con balcone e vista sul parco",
        "rooms" => 1,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 65,
        "address" => "Contrada Barone 3 Piano 4\nSettimo Gaetano terme, 87090 Bergamo (MT)",
        "visibility" => 0,
        "slug" => "fugiat-nisi-omnis-reprehenderit",
        "longitude" => -101.077928,
        "latitude" => -17.217678,
        "description" => 'Accogliente appartamento bilocale con vista panoramica sulla città. Luminoso e spazioso, questo appartamento offre un soggiorno confortevole con una cucina moderna e attrezzata. La camera da letto è dotata di ampi armadi a muro per un facile stoccaggio. Il bagno è completo di doccia e vasca da bagno. Goditi la vista mozzafiato dalla terrazza privata, perfetta per rilassarsi o intrattenere gli amici. Situato in una zona tranquilla e ben servita, questo appartamento è vicino a negozi, ristoranti e mezzi di trasporto pubblico.',
        "price" => 663959.88,
        "cover" => "https://www.loscudodistabio.ch/media/vb2nooto/studiofdi-034.jpg?width=902&height=601&format=webp&rnd=133094543498600000"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento d'epoca con soffitti alti",
        "rooms" => 2,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 135,
        "address" => "Via Pietro 27 Appartamento 73\nSan Flavio del friuli, 67284 Messina (OG)",
        "visibility" => 0,
        "slug" => "atque-dolorem-consequatur-blanditiis-et-officia",
        "longitude" => 173.379271,
        "latitude" => 32.930768,
        "description" => '',
        "price" => 114540.03,
        "cover" => "https://media.lavorincasa.it/post/18/17519/data/spazioso-appartamento-su-due-piani-sovrapposti.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Elegante appartamento con caminetto",
        "rooms" => 5,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 151,
        "address" => "Strada Michael 27 Appartamento 19\nEvita umbro, 75839 Imperia (TS)",
        "visibility" => 1,
        "slug" => "similique-odit-libero-voluptatem-et",
        "longitude" => 143.744174,
        "latitude" => 22.758526,
        "description" => '',
        "price" => 739914.05,
        "cover" => "https://www.berghotel.com/CustomerData/557/files/Images/berghotel/ihr-berghotel/zirbenappartement.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Ampio trilocale con spaziosa cucina abitabile",
        "rooms" => 4,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 93,
        "address" => "Borgo Donati 668\nSesto Ilario, 57386 Venezia (CA)",
        "visibility" => 1,
        "slug" => "aut-odit-voluptatem-sapiente-aut-necessitatibus",
        "longitude" => -178.380793,
        "latitude" => -68.981599,
        "description" => '',
        "price" => 61835.84,
        "cover" => "https://www.villaggiodellasalutepiu.it/wp-content/uploads/2020/04/WhatsApp-Image-2020-04-14-at-15.39.52-e1587547340835.jpeg"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento di charme in palazzo storico",
        "rooms" => 4,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 78,
        "address" => "Incrocio Grassi 57 Piano 2\nRusso sardo, 28502 Ravenna (AR)",
        "visibility" => 0,
        "slug" => "cumque-commodi-exercitationem-repudiandae-eaque-commodi",
        "longitude" => 62.508389,
        "latitude" => 4.981184,
        "description" => '',
        "price" => 83313.88,
        "cover" => "https://static.suedtirol.com/supercompanies/17731/images/appartamenti-caldogno0525.jpg?size=scg"
    ],
    [
        "user_id" => 1,
        "title" => "Monolocale con accesso alla piscina condominiale",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 90,
        "address" => "Via Odino 4 Piano 0\nFerretti sardo, 91849 Mantova (SO)",
        "visibility" => 1,
        "slug" => "cum-ipsa-voluptas-deserunt-aut-autem-modi-aspernatur",
        "longitude" => -15.984209,
        "latitude" => -8.196968,
        "description" => '',
        "price" => 112432.95,
        "cover" => "https://www.apartments-fill.com/bilder/Apartments-Fontana.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento vicino al centro commerciale",
        "rooms" => 4,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 143,
        "address" => "Via Rinaldi 53\nQuarto a mare, 89380 Avellino (CA)",
        "visibility" => 1,
        "slug" => "molestiae-quam-magni-est-quas-est-esse",
        "longitude" => -61.671147,
        "latitude" => -73.650871,
        "description" => '',
        "price" => 706007.95,
        "cover" => "https://www.innaosta.com/wp-content/uploads/2023/01/appartamenti-vacanza-turisti-aosta1-600x325.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Loft industriale con dettagli in mattoni a vista",
        "rooms" => 2,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 75,
        "address" => "Strada Bernardo 7\nSan Loretta laziale, 91487 Ogliastra (FG)",
        "visibility" => 0,
        "slug" => "a-fugiat-eaque-nemo-quos-consequatur-est-et",
        "longitude" => -35.140487,
        "latitude" => 63.226505,
        "description" => '',
        "price" => 522095.93,
        "cover" => "https://cdn.discordapp.com/attachments/1127889223098314815/1134034385449000970/7ea8f483daadcdf157c3be89b0041a64.webp"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento panoramico con vista mare",
        "rooms" => 1,
        "bedrooms" => 1,
        "bathrooms" => 2,
        "square_meters" => 199,
        "address" => "Contrada Longo 90\nBorgo Selvaggia veneto, 98185 Barletta-Andria-Trani (FC)",
        "visibility" => 0,
        "slug" => "nihil-qui-inventore-repellat-repellat-repellat-fugit",
        "longitude" => 77.980361,
        "latitude" => -20.548354,
        "description" => '',
        "price" => 710194.34,
        "cover" => "https://cdn.discordapp.com/attachments/1127889223098314815/1134034385855852554/mobile-tv-1_1.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Trilocale arredato con gusto",
        "rooms" => 3,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 66,
        "address" => "Strada Piras 50 Appartamento 41\nGianmaria nell'emilia, 21815 Potenza (SO)",
        "visibility" => 1,
        "slug" => "cupiditate-quos-libero-et-dolorem-voluptatibus-aperiam",
        "longitude" => -98.633618,
        "latitude" => -31.699372,
        "description" => '',
        "price" => 425507.98,
        "cover" => "https://th.bing.com/th/id/R.5ab862e2ad9705577e7b7fba5c6a455b?rik=kvOfAvQx2Pb%2bBA&pid=ImgRaw&r=0"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento con camino e terrazzo privato",
        "rooms" => 3,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 147,
        "address" => "Rotonda Ruggiero 26 Piano 8\nOsea sardo, 03163 Venezia (RE)",
        "visibility" => 1,
        "slug" => "voluptate-ea-deleniti-perspiciatis-officiis-sed",
        "longitude" => 129.380139,
        "latitude" => -32.580425,
        "description" => '',
        "price" => 390292.06,
        "cover" => "https://i.pinimg.com/originals/fc/ac/19/fcac194ad03f8af8dfaf702db8db5b0f.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Delizioso bilocale in zona tranquilla",
        "rooms" => 2,
        "bedrooms" => 1,
        "bathrooms" => 2,
        "square_meters" => 81,
        "address" => "Rotonda Claudia 3 Piano 6\nSartori terme, 15185 Cagliari (SA)",
        "visibility" => 1,
        "slug" => "suscipit-sed-molestiae-qui-iure",
        "longitude" => 164.834996,
        "latitude" => -77.665778,
        "description" => '',
        "price" => 583756.35,
        "cover" => "https://images1.apartments.com/i2/-6CF2epBzuK8xUsooaIY6WXxrMRcYoM1O_vApH7_1jc/111/trinity-club-apartments-trinity-fl-exterior.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Attico con vista sulla città e terrazza privata",
        "rooms" => 1,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 71,
        "address" => "Contrada Giordano 53 Piano 4\nLoretta sardo, 59122 Vicenza (PT)",
        "visibility" => 0,
        "slug" => "quibusdam-est-reprehenderit-eveniet-minima-qui-nobis-distinctio",
        "longitude" => 29.576808,
        "latitude" => 66.814854,
        "description" => '',
        "price" => 796810.50,
        "cover" => "https://apartmentgeeks.net/wp-content/uploads/2013/05/Gorgeous-Modern-Apartment-Design.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento ristrutturato in stile moderno",
        "rooms" => 2,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 121,
        "address" => "Piazza Montanari 974 Appartamento 83\nFerrara calabro, 18859 Lecce (ME)",
        "visibility" => 1,
        "slug" => "minus-adipisci-hic-dolorem-porro-eos",
        "longitude" => -14.042079,
        "latitude" => -38.918291,
        "description" => '',
        "price" => 511062.96,
        "cover" => "https://gofirstgreen.com/wp-content/uploads/2020/07/landscaping-for-apartment-buildings-properties-cincinnati-northern-kentucky.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Ampio quadrilocale con parcheggio interno",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 88,
        "address" => "Contrada Barone 14 Appartamento 21\nFontana laziale, 74181 Teramo (SI)",
        "visibility" => 0,
        "slug" => "nemo-aut-molestiae-enim-beatae-repudiandae",
        "longitude" => 149.298341,
        "latitude" => 51.330823,
        "description" => '',
        "price" => 204187.08,
        "cover" => "https://blog.etinet.it/wp-content/uploads/2016/07/case-dani.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento con giardino e spazio barbecue",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 61,
        "address" => "Strada Pellegrino 876 Appartamento 52\nCosetta ligure, 82274 Vercelli (CH)",
        "visibility" => 0,
        "slug" => "veniam-alias-quia-nam-dolor-ut-molestiae",
        "longitude" => -9.637507,
        "latitude" => -86.660265,
        "description" => '',
        "price" => 190660.66,
        "cover" => "http://www.case-in-legno-progettolegno.it/wp-content/uploads/2015/12/Casa-in-legno-a-Fano-0003.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Monolocale con cucina a vista",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 137,
        "address" => "Incrocio Omar 652 Appartamento 84\nMonti del friuli, 91600 Brescia (IS)",
        "visibility" => 0,
        "slug" => "a-quas-placeat-minima-enim",
        "longitude" => -102.179788,
        "latitude" => 21.095864,
        "description" => '',
        "price" => 912493.29,
        "cover" => "https://cdn.cosedicasa.com/wp-content/uploads/2013/06/check-up-casa.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento luminoso con ampie finestre",
        "rooms" => 1,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 94,
        "address" => "Incrocio Fabbri 34\nJacopo calabro, 64776 Agrigento (RA)",
        "visibility" => 1,
        "slug" => "recusandae-qui-voluptas-qui-et-hic-quidem-quo-dolorum",
        "longitude" => -102.994619,
        "latitude" => -55.982319,
        "description" => '',
        "price" => 854229.79,
        "cover" => "https://st3.idealista.it/news/archivie/styles/imagen_big_lightbox/public/2019-12/huf_haus_ap.jpg?sv=0tPOY1cT&itok=ooNtzdjh"
    ],
    [
        "user_id" => 1,
        "title" => "Bilocale con accesso alla piscina condominiale",
        "rooms" => 2,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 172,
        "address" => "Via Sala 1 Appartamento 40\nQuarto Cira ligure, 03360 Varese (SA)",
        "visibility" => 1,
        "slug" => "enim-ad-ut-est-eum-perspiciatis-esse-sed-eos",
        "longitude" => 19.152841,
        "latitude" => -56.079223,
        "description" => '',
        "price" => 978841.79,
        "cover" => "https://www.caseinlegnonaturale.it/wp-content/uploads/2018/03/Case_in_legno_tronchi_legno_massiccio_legno_lamellare_140mm_-15.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento in zona residenziale e silenziosa",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 108,
        "address" => "Via D'amico 899\nSettimo Ninfa a mare, 92492 Arezzo (RC)",
        "visibility" => 1,
        "slug" => "sequi-exercitationem-deserunt-eaque-quaerat-voluptatem-porro-voluptatem-voluptatibus",
        "longitude" => -31.852729,
        "latitude" => -85.203581,
        "description" => '',
        "price" => 362318.53,
        "cover" => "https://mondodesign.it/wp-content/uploads/2015/01/Case-Legno-Lusso-01.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Loft con soppalco e design contemporaneo",
        "rooms" => 5,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 197,
        "address" => "Borgo Clea 2 Piano 2\nAntonino salentino, 95174 Benevento (PC)",
        "visibility" => 0,
        "slug" => "qui-eos-iste-iure-architecto",
        "longitude" => 84.650044,
        "latitude" => -17.158031,
        "description" => '',
        "price" => 650683.91,
        "cover" => "https://st3.idealista.it/news/archivie/2019-06/modum_610_ebenholz_1.jpg?sv=yRByxtJs"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento in palazzo d'epoca con affreschi",
        "rooms" => 5,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 70,
        "address" => "Strada Cleopatra 38\nSettimo Raniero sardo, 87185 Novara (RN)",
        "visibility" => 0,
        "slug" => "eius-dicta-et-reiciendis-qui-in",
        "longitude" => 122.264893,
        "latitude" => 79.570736,
        "description" => '',
        "price" => 132669.94,
        "cover" => "https://www.arredamento.it/img/452/progettare-case-belle.asp_Oit_112168.webp"
    ],
    [
        "user_id" => 1,
        "title" => "Trilocale con terrazzo e vista sulle montagne",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 109,
        "address" => "Incrocio Grasso 32\nSesto Mercedes umbro, 29396 Ragusa (VC)",
        "visibility" => 1,
        "slug" => "cupiditate-et-sint-perferendis-sunt",
        "longitude" => -125.63939,
        "latitude" => 61.55705,
        "description" => '',
        "price" => 104301.06,
        "cover" => "https://cdn.discordapp.com/attachments/1127889223098314815/1134037403657568256/1d13ba24-41ae-4349-b23d-5215385ff683.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento in residence con servizi inclusi",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 101,
        "address" => "Strada Battaglia 9\nGatti calabro, 31102 Medio Campidano (RI)",
        "visibility" => 0,
        "slug" => "eos-enim-aut-et-nihil-debitis-suscipit-eveniet-modi",
        "longitude" => -100.460834,
        "latitude" => -40.772505,
        "description" => '',
        "price" => 619729.28,
        "cover" => "https://abitare.moondo.info/files/2018/01/Vantaggi-e-svantaggi-delle-case-prefabbricate.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Monolocale in zona ben servita dai mezzi pubblici",
        "rooms" => 5,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 150,
        "address" => "Strada Pellegrino 283 Appartamento 89\nLisa calabro, 86792 Padova (OT)",
        "visibility" => 1,
        "slug" => "quidem-repellat-explicabo-ipsa-unde-minima-impedit",
        "longitude" => -29.676266,
        "latitude" => -15.822127,
        "description" => '',
        "price" => 488712.45,
        "cover" => "https://www.avantgardeconstruct.it/wp-content/uploads/2019/08/case-prefabbricate-prezzi-Premium.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento con vista sulla campagna circostante",
        "rooms" => 2,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 117,
        "address" => "Piazza Leone 1 Piano 9\nSesto Isabel, 74894 Cuneo (PO)",
        "visibility" => 0,
        "slug" => "fugit-magnam-dolor-reiciendis-qui",
        "longitude" => -161.799773,
        "latitude" => -48.079935,
        "description" => '',
        "price" => 999449.48,
        "cover" => "https://www.costantinilegno.it/wp-content/uploads/2015/11/LACOST-Case-in-legno-umbria.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Bilocali completamente arredati e attrezzati",
        "rooms" => 5,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 156,
        "address" => "Strada Valentini 4\nPiersilvio del friuli, 46724 Cuneo (OT)",
        "visibility" => 0,
        "slug" => "veniam-et-sit-debitis-esse",
        "longitude" => -176.154884,
        "latitude" => 49.037301,
        "description" => '',
        "price" => 823267.47,
        "cover" => "https://pro2-bar-s3-cdn-cf2.myportfolio.com/018c37874d387a698f31dfe0e8634a5f/3716f3106f98b11bc8870ecf_rw_1920.jpg?h=16b52759e189f63d3897d8ada6422dbf"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento con cucina spaziosa e moderna",
        "rooms" => 4,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 128,
        "address" => "Rotonda Hector 481\nFerrari a mare, 20668 Oristano (PD)",
        "visibility" => 1,
        "slug" => "earum-aut-temporibus-odit-et",
        "longitude" => -19.909563,
        "latitude" => -13.795162,
        "description" => '',
        "price" => 645898.75,
        "cover" => "https://media.tio.ch/files/domains/tio.ch/images/4bsi/-case-prefabbricate-in-cemento-cinque-buoni-motivi-per-pensarci-hqc9.jpg?v=1"
    ],
    [
        "user_id" => 1,
        "title" => "Loft con aria condizionata e ampio spazio living",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 132,
        "address" => "Rotonda Miriana 866 Appartamento 23\nSirio nell'emilia, 45928 Roma (VV)",
        "visibility" => 0,
        "slug" => "et-aut-ipsam-perspiciatis-id",
        "longitude" => 15.861108,
        "latitude" => -23.841515,
        "description" => '',
        "price" => 268394.02,
        "cover" => "https://cdn.discordapp.com/attachments/1127889223098314815/1134037845661732894/tecnoedil-avezzano-case-in-legno-mobile.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento con garage e parcheggio privato",
        "rooms" => 3,
        "bedrooms" => 2,
        "bathrooms" => 1,
        "square_meters" => 119,
        "address" => "Piazza Adriano 307\nPellegrino veneto, 04090 La Spezia (BI)",
        "visibility" => 0,
        "slug" => "qui-ipsa-id-omnis-dignissimos",
        "longitude" => 171.679232,
        "latitude" => -33.687831,
        "description" => '',
        "price" => 763899.83,
        "cover" => "https://www.casapratica.org/casa/sistemare-casa/case-moderne_NG1.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Trilocale con accesso a piscina e palestra",
        "rooms" => 3,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 128,
        "address" => "Rotonda Tancredi 87 Appartamento 58\nRinaldi nell'emilia, 82574 Latina (TR)",
        "visibility" => 0,
        "slug" => "consequatur-rerum-aut-omnis-nemo",
        "longitude" => 27.416815,
        "latitude" => -8.729172,
        "description" => '',
        "price" => 511345.99,
        "cover" => "https://www.freedompress.cc/wp-content/uploads/2021/02/casa-singola.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento vicino alle principali attrazioni turistiche",
        "rooms" => 1,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 51,
        "address" => "Incrocio Fernando 34\nOrtensia nell'emilia, 77892 Belluno (GE)",
        "visibility" => 0,
        "slug" => "nostrum-accusantium-iure-minima-et-praesentium-voluptatibus",
        "longitude" => 147.287666,
        "latitude" => -0.72831,
        "description" => '',
        "price" => 924085.26,
        "cover" => "https://i.pinimg.com/originals/11/1b/9e/111b9e824ad69edbce9c28be542cbce7.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Bilocale con terrazza e vista sul lago",
        "rooms" => 5,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 95,
        "address" => "Borgo Bacchisio 61 Piano 9\nSan Joey, 14129 Biella (OR)",
        "visibility" => 1,
        "slug" => "velit-consequatur-laborum-sit-numquam-et-nostrum-aut",
        "longitude" => -40.022229,
        "latitude" => -6.084489,
        "description" => '',
        "price" => 497408.07,
        "cover" => "https://i.pinimg.com/originals/6a/ad/f0/6aadf01d9e9b2df74036c989e896b419.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento in condominio con servizio di portineria",
        "rooms" => 4,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 196,
        "address" => "Incrocio Ileana 55 Appartamento 20\nSan Alberto, 77066 Caserta (AN)",
        "visibility" => 1,
        "slug" => "id-quis-excepturi-nostrum-eaque-repudiandae",
        "longitude" => -129.799236,
        "latitude" => -39.22308,
        "description" => '',
        "price" => 277072.08,
        "cover" => "https://www.roadcalls.fr/wp-content/uploads/2017/02/stockholm_belle_ville_europe.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Loft con cucina a isola e finiture di lusso",
        "rooms" => 1,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 95,
        "address" => "Incrocio Moretti 1 Appartamento 01\nSesto Samira, 86412 Siena (VC)",
        "visibility" => 1,
        "slug" => "in-est-delectus-culpa-pariatur-officia-nemo-reprehenderit",
        "longitude" => -127.803153,
        "latitude" => -75.014053,
        "description" => '',
        "price" => 510611.25,
        "cover" => "https://st3.idealista.it/news/archivie/styles/imagen_big_lightbox/public/2021-06/dsc3853-high.jpg?sv=Omwz7Y4T&itok=Eng97CFq"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento con camino e pavimenti in parquet",
        "rooms" => 3,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 174,
        "address" => "Borgo Siro 971 Appartamento 94\nQuarto Fulvio, 73559 Viterbo (PU)",
        "visibility" => 0,
        "slug" => "ut-quis-ipsam-blanditiis-fugit-neque",
        "longitude" => 88.29448,
        "latitude" => -85.979675,
        "description" => '',
        "price" => 962564.43,
        "cover" => "https://i.pinimg.com/originals/37/1c/9c/371c9cb6f72da156b0058df1fa3365f8.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Monolocale con angolo cottura e bagno privato",
        "rooms" => 2,
        "bedrooms" => 1,
        "bathrooms" => 1,
        "square_meters" => 172,
        "address" => "Strada Martinelli 424\nMuzio sardo, 37725 Benevento (PV)",
        "visibility" => 1,
        "slug" => "necessitatibus-rerum-porro-impedit-doloribus-veritatis-earum-laboriosam-ullam",
        "longitude" => 140.747645,
        "latitude" => 53.534841,
        "description" => '',
        "price" => 972156.40,
        "cover" => "https://i.pinimg.com/originals/07/2f/c3/072fc3e1eda96c42caca12dae2bcfb2d.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento con vista sul fiume e balcone",
        "rooms" => 3,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 176,
        "address" => "Rotonda Pellegrino 93\nBorgo Mariano lido, 44596 Macerata (MT)",
        "visibility" => 0,
        "slug" => "nemo-ipsa-exercitationem-fugiat-facilis-ut-numquam-et",
        "longitude" => -47.717734,
        "latitude" => -11.925305,
        "description" => '',
        "price" => 104657.89,
        "cover" => "https://www.luxgallery.it/wp-content/uploads/2021/04/R40d76d38881db98a4556b16777d48324.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Trilocale con spazio esterno e area relax",
        "rooms" => 1,
        "bedrooms" => 2,
        "bathrooms" => 2,
        "square_meters" => 200,
        "address" => "Rotonda Ricci 606\nGenziana umbro, 41178 Bergamo (TE)",
        "visibility" => 0,
        "slug" => "vel-reprehenderit-quia-soluta-quisquam",
        "longitude" => 107.143184,
        "latitude" => -65.334232,
        "description" => '',
        "price" => 175239.83,
        "cover" => "https://www.piscine-verona.it/wp-content/uploads/2018/07/piscina-di-lusso.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Appartamento arredato con mobili di design",
        "rooms" => 3,
        "bedrooms" => 3,
        "bathrooms" => 1,
        "square_meters" => 65,
        "address" => "Borgo Jelena 69 Appartamento 85\nQuarto Ursula, 19124 Viterbo (VA)",
        "visibility" => 1,
        "slug" => "praesentium-autem-velit-commodi",
        "longitude" => -79.530826,
        "latitude" => -17.849932,
        "description" => '',
        "price" => 482841.79,
        "cover" => "https://mondodesign.it/wp-content/uploads/2015/01/Case-Legno-Lusso-14.jpg"
    ],
    [
        "user_id" => 1,
        "title" => "Loft con soppalco e grandi finestre panoramiche",
        "rooms" => 5,
        "bedrooms" => 3,
        "bathrooms" => 2,
        "square_meters" => 136,
        "address" => "Via Sala 13 Piano 7\nSettimo Tosca, 81131 Messina (BG)",
        "visibility" => 1,
        "slug" => "dicta-pariatur-ut-provident-odit-consequuntur-eius-voluptatem",
        "longitude" => -51.954328,
        "latitude" => 0.244157,
        "description" => '',
        "price" => 638576.18,
        "cover" => "https://blogdilifestyle.it/wp-content/uploads/2017/12/case-di-lusso-1920x1080.jpg"
    ]
];